# Generated by Django 4.1.2 on 2022-11-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo", old_name="important_check", new_name="important",
        ),
        migrations.AlterField(
            model_name="todo",
            name="datecompleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
